# Generated by Django 3.2.13 on 2022-06-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicalentity',
            options={'verbose_name_plural': 'Geographical Entities'},
        ),
        migrations.AlterField(
            model_name='geographicalentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='georepo.geographicalentity'),
        ),
    ]
