# Generated by Django 3.2.13 on 2022-06-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0004_dataset_vector_tiles_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('code_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.codecl')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.geographicalentity')),
            ],
        ),
    ]
