# Generated by Django 3.2.13 on 2022-06-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0005_codecl_entitycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('style', models.JSONField(blank=True, choices=[('fill', 'Fill'), ('line', 'Line'), ('symbol', 'Symbol'), ('circle', 'Circle')], null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.dataset')),
            ],
        ),
    ]
