# Generated by Django 3.2.13 on 2022-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0006_layerstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerstyle',
            name='type',
            field=models.CharField(blank=True, choices=[('fill', 'Fill'), ('line', 'Line'), ('symbol', 'Symbol'), ('circle', 'Circle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='layerstyle',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
