# Generated by Django 3.2.13 on 2022-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0008_auto_20220614_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerstyle',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
