# Generated by Django 3.2.13 on 2022-06-27 01:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0010_dataset_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalentity',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
