# Generated by Django 4.0.6 on 2022-08-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0013_alter_dataset_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTilingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTypeTilingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplify_tolerance', models.FloatField(default=0)),
                ('dataset_tiling_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.datasettilingconfig')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.entitytype')),
            ],
        ),
    ]
