# Generated by Django 4.0.6 on 2022-08-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0014_datasettilingconfig_entitytypetilingconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasettilingconfig',
            options={'ordering': ['dataset__label', 'zoom_level']},
        ),
    ]
