# Generated by Django 4.0.6 on 2022-09-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0016_dataset_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='qc_notes',
            field=models.TextField(blank=True, null=True, verbose_name='QC Notes'),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='uuid_versioned',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='geographicalentity',
            name='is_latest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
