# Generated by Django 4.0.7 on 2022-10-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0023_dataset_created_at_dataset_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
