# Generated by Django 4.0.7 on 2022-10-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0024_geographicalentity_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicalentity',
            name='uuid_versioned',
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='unique_code_version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
