# Generated by Django 4.0.7 on 2022-10-28 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0025_remove_geographicalentity_uuid_versioned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicalentity',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Geographical Entities'},
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='uuid_revision',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
