# Generated by Django 4.0.7 on 2022-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0026_alter_geographicalentity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='revision_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
