# Generated by Django 4.0.7 on 2022-10-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0028_dataset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
