# Generated by Django 4.0.7 on 2022-11-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0030_remove_geographicalentity_dataset_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='georepo.geographicalentity'),
        ),
    ]
