# Generated by Django 4.0.7 on 2022-11-11 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initialize_idtypes(apps, schema_editor):
    # insert PCode and Id
    IdType = apps.get_model('georepo', 'IdType')
    if not IdType.objects.exists():
        IdType.objects.create(
            name='PCode'
        )
        IdType.objects.create(
            name='Id'
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0031_alter_geographicalentity_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(initialize_idtypes),
    ]
