# Generated by Django 4.0.7 on 2022-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0032_idtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityname',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
