# Generated by Django 4.0.7 on 2022-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0033_entityname_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='feature_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='line_resolution',
            field=models.FloatField(blank=True, help_text='The average resolution or distance between line vertices. Calculated as the total perimeter of all boundary units divided by the total number of vertices.', null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='perimeter',
            field=models.FloatField(blank=True, help_text='The total length of borders', null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='vertex_density',
            field=models.FloatField(blank=True, help_text='The average number of vertices for every km of line distance. Calculated as the total number of vertices of all boundary units divided by the total perimeter.', null=True),
        ),
        migrations.AddField(
            model_name='geographicalentity',
            name='vertices',
            field=models.PositiveIntegerField(blank=True, help_text='The total number of line vertices', null=True),
        ),
    ]
