# Generated by Django 4.0.7 on 2022-11-15 06:17

from django.db import migrations, models
import django.db.models.deletion


def init_entity_id(apps, schema_editor):
    EntityId = apps.get_model('georepo', 'EntityId')
    IdType = apps.get_model('georepo', 'IdType')
    pCode = IdType.objects.get(name='PCode')
    GeographicalEntity = apps.get_model('georepo', 'GeographicalEntity')
    entity_list = GeographicalEntity.objects.all()
    for entity in entity_list.iterator():
        EntityId.objects.create(
            geographical_entity=entity,
            code=pCode,
            value=entity.internal_code,
            default=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0034_geographicalentity_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.idtype')),
                ('geographical_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.geographicalentity')),
            ],
        ),
        migrations.RunPython(init_entity_id),
    ]
