# Generated by Django 4.0.7 on 2022-11-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0035_entityid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entityid',
            index=models.Index(fields=['value'], name='georepo_ent_value_815329_idx'),
        ),
        migrations.AddIndex(
            model_name='entityname',
            index=models.Index(fields=['name'], name='georepo_ent_name_211c78_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicalentity',
            index=models.Index(fields=['internal_code'], name='georepo_geo_interna_032dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicalentity',
            index=models.Index(fields=['label'], name='georepo_geo_label_3b51ff_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicalentity',
            index=models.Index(fields=['level'], name='georepo_geo_level_bfea81_idx'),
        ),
        migrations.AddIndex(
            model_name='geographicalentity',
            index=models.Index(fields=['revision_number'], name='georepo_geo_revisio_f6e6c2_idx'),
        ),
    ]
