# Generated by Django 4.0.7 on 2022-11-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0036_entityid_georepo_ent_value_815329_idx_and_more'),
        ('georepo', '0036_remove_datasetview_datasets_and_more'),
    ]

    operations = [
    ]
