# Generated by Django 4.0.7 on 2022-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0037_merge_20221129_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='bbox',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('DO', 'Done'), ('ER', 'Error')], default='PE', max_length=2),
        ),
    ]
