# Generated by Django 4.0.7 on 2022-12-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0042_entitysimplified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicalentity',
            name='simplified_geometry',
        ),
    ]
