# Generated by Django 4.0.7 on 2022-12-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0042_merge_0039_add_trigram_ext_0041_dataset_trigger_view'),
        ('georepo', '0044_geographicalentity_ancestor'),
    ]

    operations = [
    ]
