# Generated by Django 4.0.7 on 2023-01-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0046_adminleveltilingconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityTypeTilingConfig',
        ),
    ]
