# Generated by Django 4.0.7 on 2023-01-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0048_alter_entityid_geographical_entity'),
        ('georepo', '0048_dataset_style_source_name_dataset_styles'),
    ]

    operations = [
    ]
