# Generated by Django 4.0.7 on 2023-01-15 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0049_merge_20230112_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalentity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='concept UUID'),
        ),
        migrations.AlterField(
            model_name='geographicalentity',
            name='uuid_revision',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='uuid for each revision'),
        ),
    ]
