# Generated by Django 4.0.7 on 2023-01-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0050_alter_geographicalentity_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityname',
            name='geographical_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_names', to='georepo.geographicalentity'),
        ),
    ]
