# Generated by Django 4.0.7 on 2023-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0051_alter_entityname_geographical_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
