# Generated by Django 4.0.7 on 2023-01-18 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0052_language_native_name_language_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID'),
        ),
    ]
