# Generated by Django 4.0.7 on 2023-01-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0052_dataset_geometry_similarity_threshold_new_and_more'),
        ('georepo', '0053_datasetview_uuid'),
    ]

    operations = [
    ]
