# Generated by Django 4.0.7 on 2023-01-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0057_dataset_simplification_task_id'),
        ('georepo', '0057_datasetview_default_ancestor_code_and_more'),
    ]

    operations = [
    ]
