# Generated by Django 4.0.7 on 2023-01-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0058_merge_20230130_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='admin_level_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DatasetAdminLevelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georepo.dataset')),
            ],
        ),
    ]
