# Generated by Django 4.0.7 on 2023-01-30 08:34

from django.db import migrations, models
import uuid


def patch_module_uuid(apps, schema_editor):
    Module = apps.get_model('georepo', 'Module')
    modules = Module.objects.all()
    for module in modules:
        module.uuid = uuid.uuid4()
        module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0058_merge_20230130_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.RunPython(patch_module_uuid),
    ]
