# Generated by Django 4.0.7 on 2023-02-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0059_geographicalentity_admin_level_name_and_more'),
        ('georepo', '0059_module_uuid'),
    ]

    operations = [
    ]
