# Generated by Django 4.0.7 on 2023-02-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0060_alter_datasetadminlevelname_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
