# Generated by Django 4.0.7 on 2023-01-30 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0060_dataset_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='tiles_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
