# Generated by Django 4.0.7 on 2023-02-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0060_alter_datasetadminlevelname_label'),
        ('georepo', '0060_dataset_short_code'),
        ('georepo', '0060_merge_20230203_0434'),
    ]

    operations = [
    ]
