# Generated by Django 4.0.7 on 2023-02-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0061_datasetview_tiles_updated_at'),
        ('georepo', '0061_merge_20230203_0434'),
    ]

    operations = [
    ]
