# Generated by Django 4.0.7 on 2023-02-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0061_datasetview_last_update'),
        ('georepo', '0062_merge_20230203_0435'),
    ]

    operations = [
    ]
