# Generated by Django 4.0.7 on 2023-02-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0063_merge_20230203_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetview',
            name='bbox',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
