# Generated by Django 4.0.7 on 2023-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0064_alter_datasetview_bbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
