# Generated by Django 4.0.7 on 2023-01-23 08:33

from django.db import migrations


def add_new_line_boundary_module(apps, schema_editor):
    Module = apps.get_model('georepo', 'Module')
    module_name = 'Boundary Lines'
    check_exist = Module.objects.filter(
        name=module_name
    ).exists()
    if not check_exist:
        Module.objects.create(
            name=module_name,
            dataset_entity_name='Country',
            dataset_entity_name_plural='Countries'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0065_module_description'),
    ]

    operations = [
        migrations.RunPython(add_new_line_boundary_module),
    ]
