# Generated by Django 4.0.7 on 2023-02-10 02:50

from django.db import connection
from django.db import migrations


def clear_view(apps, schema_editor):
    with connection.cursor() as cursor:
        select_views_sql = (
            "SELECT 'DROP VIEW \"' || table_name || '\";' "
            'FROM information_schema.views '
            "WHERE table_schema NOT IN ('pg_catalog', 'information_schema') "
            "AND table_name NOT IN ('geography_columns', 'geometry_columns', "
            "'raster_columns', 'raster_overviews') "
            "AND table_name !~ '^pg_'"
        )
        cursor.execute(select_views_sql)
        queries = cursor.fetchall()
        for query in queries:
            cursor.execute(query[0])


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0067_datasetadminlevelname_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_view),
    ]
