# Generated by Django 4.0.7 on 2023-02-09 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0069_alter_geographicalentity_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitysimplified',
            name='simplified_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
