# Generated by Django 4.0.7 on 2023-02-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0066_tagwithdescription_taggedrecord_datasetview_tags'),
        ('georepo', '0070_alter_entitysimplified_simplified_geometry'),
    ]

    operations = [
    ]
