# Generated by Django 4.0.7 on 2023-03-05 08:40

from django.db import migrations, models


def patch_label_entity_name(apps, schema_editor):
    GeographicalEntity = apps.get_model('georepo', 'GeographicalEntity')
    EntityName = apps.get_model('georepo', 'EntityName')
    entity_list = GeographicalEntity.objects.all()
    for entity in entity_list.iterator(chunk_size=1):
        names = EntityName.objects.filter(
            geographical_entity=entity
        ).order_by('id')
        for index, name in enumerate(names):
            name.label = ''
            name.idx = index
            name.save()


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0074_entityname_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityname',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(patch_label_entity_name),
    ]
