# Generated by Django 4.0.7 on 2023-03-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0075_entityname_idx'),
        ('georepo', '0075_update_view_tags'),
    ]

    operations = [
    ]
