# Generated by Django 4.0.7 on 2023-03-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0081_dataset_max_privacy_level_dataset_min_privacy_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetview',
            options={'permissions': [('edit_metadata_dataset_view', 'Edit metadata view'), ('edit_query_dataset_view', 'Edit SQL query')]},
        ),
    ]
