# Generated by Django 4.0.7 on 2023-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0082_alter_datasetview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='bbox',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
