# Generated by Django 4.0.7 on 2023-03-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def patch_existing_users(apps, schema_editor):
    Dataset = apps.get_model('georepo', 'Dataset')
    User = apps.get_model('auth', 'User')
    GeorepoRole = apps.get_model('georepo', 'GeorepoRole')
    for user in User.objects.all():
        type = 'Viewer'
        has_dataset = Dataset.objects.filter(
            created_by=user
        ).exists()
        if has_dataset or user.is_superuser:
            type = 'Creator'
        GeorepoRole.objects.create(
            user=user,
            type=type
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0085_patch_existing_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeorepoRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Creator', 'Creator'), ('Viewer', 'Viewer')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(patch_existing_users),
    ]
