# Generated by Django 4.0.7 on 2023-03-15 06:44

from django.db import migrations


def add_unicef_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    unicef_group, _ = Group.objects.get_or_create(
        name='UNICEF'
    )
    User = apps.get_model('auth', 'User')
    users = User.objects.filter(
        is_superuser=False
    )
    for user in users:
        user.groups.add(unicef_group)


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0086_georeporole'),
    ]

    operations = [
        migrations.RunPython(add_unicef_group),
    ]
