# Generated by Django 4.0.7 on 2023-03-15 07:20

from django.db import migrations


def populate_view_resources(apps, schema_editor):
    DatasetView = apps.get_model('georepo', 'DatasetView')
    DatasetViewResource = apps.get_model('georepo', 'DatasetViewResource')
    views = DatasetView.objects.all()
    for view in views:
        DatasetViewResource.objects.get_or_create(
            dataset_view=view,
            privacy_level=1
        )
        DatasetViewResource.objects.get_or_create(
            dataset_view=view,
            privacy_level=2
        )
        DatasetViewResource.objects.get_or_create(
            dataset_view=view,
            privacy_level=3
        )
        DatasetViewResource.objects.get_or_create(
            dataset_view=view,
            privacy_level=4
        )


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0087_add_unicef_group'),
    ]

    operations = [
        migrations.RunPython(populate_view_resources),
    ]
