# Generated by Django 4.0.7 on 2023-04-10 03:10

from django.db import migrations


def create_geosight_api_keys_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    GeorepoRole = apps.get_model('georepo', 'GeorepoRole')
    user, _ = User.objects.get_or_create(
        username='geosight_api_key_level_1',
        is_active=True
    )
    GeorepoRole.objects.get_or_create(
        user=user,
        type='Viewer'
    )
    user, _ = User.objects.get_or_create(
        username='geosight_api_key_level_4',
        is_active=True
    )
    GeorepoRole.objects.get_or_create(
        user=user,
        type='Viewer'
    )


def reverse_geosight_api_keys_users(apps, schema_editor):
    """Do nothing for reverse func"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0090_alter_dataset_geometry_similarity_threshold_new_and_more'),
    ]

    operations = [
        migrations.RunPython(create_geosight_api_keys_users, reverse_geosight_api_keys_users),
    ]
