# Generated by Django 4.0.7 on 2023-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0091_init_geosight_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalentity',
            name='concept_ucode',
            field=models.CharField(blank=True, default='', help_text='Concept UCode', max_length=255),
        ),
        migrations.AddIndex(
            model_name='geographicalentity',
            index=models.Index(fields=['concept_ucode'], name='georepo_geo_concept_7e88eb_idx'),
        ),
    ]
