# Generated by Django 4.0.7 on 2023-05-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0092_geographicalentity_concept_ucode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetview',
            options={'permissions': [('edit_metadata_dataset_view', 'Edit metadata view'), ('edit_query_dataset_view', 'Edit SQL query'), ('ext_view_datasetview_level_1', 'Read View - Level 1'), ('ext_view_datasetview_level_2', 'Read View - Level 2'), ('ext_view_datasetview_level_3', 'Read View - Level 3'), ('ext_view_datasetview_level_4', 'Read View - Level 4')]},
        ),
    ]
