# Generated by Django 4.0.7 on 2023-05-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0092_alter_georeporole_type'),
        ('georepo', '0092_geographicalentity_concept_ucode_and_more'),
    ]

    operations = [
    ]
