# Generated by Django 4.0.7 on 2023-05-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0093_merge_20230512_0328'),
        ('georepo', '0094_dataset_deprecated_at_dataset_deprecated_by_and_more'),
    ]

    operations = [
    ]
