# Generated by Django 4.0.7 on 2023-05-29 05:18

from django.db import migrations


def remove_validation_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    validate_task = PeriodicTask.objects.filter(
        task='validate_ready_uploads'
    ).first()
    if validate_task:
        validate_task.delete()


def revert_remove_validation_task(apps, schema_editor):
    # do nothing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0096_module_deactivated_at_module_deactivated_by_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_validation_task, revert_remove_validation_task),
    ]
