# Generated by Django 4.0.7 on 2023-07-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0098_useraccessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitysimplified',
            name='max_zoom_level',
        ),
        migrations.RemoveField(
            model_name='entitysimplified',
            name='min_zoom_level',
        ),
    ]
