# Generated by Django 4.0.7 on 2023-07-10 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0101_dataset_simplification_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTilingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=256)),
                ('zoom_level', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('simplify_tolerance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
