# Generated by Django 4.0.7 on 2023-07-27 08:46

from django.db import migrations


def add_admin_boundaries_module(apps, schema_editor):
    Module = apps.get_model('georepo', 'Module')
    module_name = 'Admin Boundaries'
    check_exist = Module.objects.filter(
        name=module_name
    ).exists()
    if not check_exist:
        Module.objects.create(
            name=module_name,
            dataset_entity_name='Country',
            dataset_entity_name_plural='Countries'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0103_alter_dataset_simplification_progress'),
    ]

    operations = [
        migrations.RunPython(add_admin_boundaries_module),
    ]
