# Generated by Django 4.0.7 on 2023-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0104_create_admin_boundaries'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entitytype',
            constraint=models.UniqueConstraint(fields=('label',), name='unique_entity_type_label'),
        ),
    ]
