# Generated by Django 4.0.7 on 2023-08-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0105_entitytype_unique_entity_type_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='vector_tiles_size',
            field=models.FloatField(default=0),
        ),
    ]
