# Generated by Django 4.0.7 on 2023-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0106_datasetviewresource_vector_tiles_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='entity_count',
            field=models.IntegerField(default=0),
        ),
    ]
