# Generated by Django 4.0.7 on 2023-09-06 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0107_datasetviewresource_entity_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryEntitySimplified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=256)),
                ('simplify_tolerance', models.FloatField(default=0)),
                ('simplified_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('geographical_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.geographicalentity')),
            ],
        ),
    ]
