# Generated by Django 4.0.7 on 2023-09-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0108_dataset_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('Syncing', 'Syncing'), ('Synced', 'Synced')], default='Synced', max_length=15),
        ),
    ]
