# Generated by Django 4.0.7 on 2023-09-13 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0108_dataset_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=256)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
