# Generated by Django 4.0.7 on 2023-09-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0108_dataset_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetViewResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=256)),
                ('logs', models.JSONField(blank=True, default=dict, help_text='Logs of upload', null=True)),
                ('dataset_view_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georepo.datasetviewresource')),
            ],
        ),
    ]
