# Generated by Django 4.0.7 on 2023-09-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0109_backgroundtask'),
        ('georepo', '0109_datasetviewresourcelog'),
    ]

    operations = [
    ]
