# Generated by Django 4.0.7 on 2023-09-15 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0110_datasetview_is_tiling_config_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetviewresource',
            old_name='data_product_task_id',
            new_name='product_task_id',
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='geojson_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='geojson_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='kml_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='kml_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='product_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='shapefile_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='shapefile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='topojson_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='topojson_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
    ]
