# Generated by Django 4.0.7 on 2023-09-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0110_dataset_is_simplified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='product_task_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
