# Generated by Django 4.0.7 on 2023-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0110_datasetviewresource_data_product_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetview',
            name='sync_status',
        ),
        migrations.AddField(
            model_name='datasetview',
            name='is_tiling_config_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='product_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='vector_tile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='product_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='vector_tile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced')], default='out_of_sync', max_length=15),
        ),
    ]
