# Generated by Django 4.0.7 on 2023-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0112_dataset_is_simplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='product_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='vector_tiles_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
