# Generated by Django 4.0.7 on 2023-09-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0111_datasetview_product_task_id'),
        ('georepo', '0112_datasetviewresource_vector_tile_detail_logs_and_more'),
    ]

    operations = [
    ]
