# Generated by Django 4.0.7 on 2023-09-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0116_datasetviewresource_product_current_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='simplification_current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simplification_current_task', to='georepo.backgroundtask'),
        ),
    ]
