# Generated by Django 4.0.7 on 2023-09-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0118_alter_datasetviewresource_product_current_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='status',
            field=models.CharField(blank=True, choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Stopped', 'Stopped with error'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Invalidated', 'Invalidated')], max_length=255, null=True),
        ),
    ]
