# Generated by Django 4.0.7 on 2023-09-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0119_alter_backgroundtask_status'),
        ('georepo', '0119_alter_dataset_label_and_more'),
    ]

    operations = [
    ]
