# Generated by Django 4.0.7 on 2023-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0122_geographicalentity_bbox_geographicalentity_centroid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='viewadminleveltilingconfig',
            index=models.Index(fields=['view_tiling_config', 'level', 'simplify_tolerance'], name='georepo_vie_view_ti_9b07a3_idx'),
        ),
    ]
