# Generated by Django 4.0.7 on 2023-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0124_dataset_simplification_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='simplification_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='simplification_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetview',
            name='product_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetview',
            name='vector_tile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='geojson_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='kml_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='product_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='shapefile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='topojson_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasetviewresource',
            name='vector_tile_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
    ]
