# Generated by Django 4.0.7 on 2023-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0125_datasetview_simplification_sync_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
