# Generated by Django 4.0.7 on 2023-11-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0128_geocodingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodingrequest',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='layer_files/%Y/%m/%d/'),
        ),
    ]
