# Generated by Django 4.0.7 on 2023-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0129_alter_geocodingrequest_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodingrequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
