# Generated by Django 4.0.7 on 2023-11-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0130_alter_geocodingrequest_submitted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchidrequest',
            name='output',
        ),
        migrations.AddField(
            model_name='searchidrequest',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='geocoding/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='searchidrequest',
            name='output_id_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
