# Generated by Django 4.0.7 on 2023-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0131_remove_searchidrequest_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchidrequest',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='search_id/%Y/%m/%d/'),
        ),
    ]
