# Generated by Django 4.0.7 on 2023-11-27 09:12

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0132_alter_searchidrequest_output_file'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            'create index name_trgm_idx on georepo_entityname '
            'using gin (name gin_trgm_ops);',
            reverse_sql='drop index name_trgm_idx;'
        ),
    ]
