# Generated by Django 4.0.7 on 2024-01-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0133_auto_20231127_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityEditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entity_old', models.JSONField(blank=True, default=dict, null=True)),
                ('entity_new', models.JSONField(blank=True, default=dict, null=True)),
                ('geographical_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.geographicalentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
