# Generated by Django 4.0.7 on 2024-01-22 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0134_entityedithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('submitted_on', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('last_min_poll_count', models.IntegerField(default=0)),
                ('last_min_poll_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(choices=[('GEOJSON', 'GEOJSON'), ('SHAPEFILE', 'SHAPEFILE'), ('KML', 'KML'), ('TOPOJSON', 'TOPOJSON')], max_length=255)),
                ('is_simplified_entities', models.BooleanField(default=False)),
                ('simplification_zoom_level', models.IntegerField(blank=True, null=True)),
                ('status_text', models.CharField(blank=True, max_length=255, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('download_link', models.TextField(blank=True, null=True)),
                ('download_link_expired_on', models.DateTimeField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='exporter/%Y/%m/%d/')),
                ('dataset_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.datasetview')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
