# Generated by Django 4.0.7 on 2024-01-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0136_backgroundtask_temporary_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
