# Generated by Django 4.0.7 on 2024-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0137_alter_exportrequest_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='source',
            field=models.CharField(blank=True, help_text='API or dashboard', max_length=255, null=True),
        ),
    ]
