# Generated by Django 4.0.7 on 2024-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0138_exportrequest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='file_output_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
