# Generated by Django 4.0.7 on 2024-01-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0139_exportrequest_file_output_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='centroid_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
