# Generated by Django 4.0.7 on 2024-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0142_remove_datasetview_product_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='centroid_sync_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='centroid_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='centroid_sync_progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='centroid_sync_status',
            field=models.CharField(choices=[('out_of_sync', 'Out of Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Stopped with error')], default='out_of_sync', max_length=15),
        ),
        migrations.AddField(
            model_name='datasetviewresource',
            name='centroid_task_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
