# Generated by Django 4.0.7 on 2024-05-21 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0143_datasetview_centroid_sync_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='centroid_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
