# Generated by Django 4.0.7 on 2024-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0145_datasetviewresource_vector_tiles_code_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetviewresource',
            name='max_zoom',
            field=models.IntegerField(default=8),
        ),
    ]
