# Generated by Django 4.0.7 on 2025-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0147_dataset_is_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='resources',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
