# Generated by Django 4.0.6 on 2022-07-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerUploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=256)),
                ('layer_name_format', models.CharField(max_length=256)),
                ('layer_code_format', models.CharField(max_length=256)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Processing', 'Processing')], max_length=128)),
                ('progress', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayerFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_id', models.CharField(blank=True, default='', max_length=256)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('layer_file', models.FileField(upload_to='layer_files/%Y/%m/%d/')),
                ('processed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('level', models.CharField(blank=True, default='', max_length=128)),
                ('entity_type', models.CharField(blank=True, default='', max_length=256)),
                ('layer_upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.layeruploadsession')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
