# Generated by Django 4.0.6 on 2022-07-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layeruploadsession',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Error', 'Error'), ('Processing', 'Processing')], max_length=128),
        ),
    ]
