# Generated by Django 4.0.6 on 2022-07-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_layeruploadsession_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
