# Generated by Django 4.0.7 on 2022-10-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_layeruploadsession_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='id_fields',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='location_type_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='name_fields',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='parent_id_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='source_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
