# Generated by Django 4.0.7 on 2022-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_layerfile_id_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='feature_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
