# Generated by Django 4.0.7 on 2022-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0023_dataset_created_at_dataset_created_by_and_more'),
        ('dashboard', '0010_layeruploadsession_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='entities',
            field=models.ManyToManyField(blank=True, null=True, to='georepo.geographicalentity'),
        ),
    ]
