# Generated by Django 4.0.7 on 2022-10-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0023_dataset_created_at_dataset_created_by_and_more'),
        ('dashboard', '0011_layeruploadsession_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layeruploadsession',
            name='entities',
        ),
        migrations.AlterField(
            model_name='layeruploadsession',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Validating', 'Validating'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Error', 'Error'), ('Processing', 'Processing')], max_length=128),
        ),
        migrations.CreateModel(
            name='EntityUploadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Valid', 'Valid'), ('Error', 'Error'), ('Processing', 'Processing')], default='', max_length=100)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('original_geographical_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_geographical_entity', to='georepo.geographicalentity')),
                ('revised_geographical_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_geographical_entity', to='georepo.geographicalentity')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.layeruploadsession')),
            ],
        ),
    ]
