# Generated by Django 4.0.7 on 2022-10-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_entityuploadstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='last_step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
