# Generated by Django 4.0.7 on 2022-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_entityuploadstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='error_summaries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
