# Generated by Django 4.0.7 on 2022-11-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0034_geographicalentity_area_and_more'),
        ('dashboard', '0020_layerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_match', models.BooleanField(default=None)),
                ('name_similarity', models.FloatField(blank=True, null=True)),
                ('geometry_overlap', models.FloatField(blank=True, null=True)),
                ('centroid_distance', models.FloatField(blank=True, null=True)),
                ('comparison_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_boundary', to='georepo.geographicalentity')),
                ('main_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_boundary', to='georepo.geographicalentity')),
            ],
        ),
    ]
