# Generated by Django 4.0.7 on 2022-11-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_layerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerconfig',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
