# Generated by Django 4.0.7 on 2022-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_boundarycomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundarycomparison',
            name='code_match',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
