# Generated by Django 4.0.7 on 2022-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_boundarycomparison_code_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='layer_type',
            field=models.CharField(blank=True, choices=[('GEOJSON', 'GEOJSON'), ('SHAPEFILE', 'SHAPEFILE'), ('GEOPACKAGE', 'GEOPACKAGE')], default='GEOJSON', max_length=100),
        ),
    ]
