# Generated by Django 4.0.7 on 2022-11-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_layerconfig_entity_type'),
        ('dashboard', '0022_alter_boundarycomparison_code_match'),
    ]

    operations = [
    ]
