# Generated by Django 4.0.7 on 2022-11-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_layerfile_layer_type'),
        ('dashboard', '0023_merge_20221114_0924'),
    ]

    operations = [
    ]
