# Generated by Django 4.0.7 on 2022-11-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0034_geographicalentity_area_and_more'),
        ('dashboard', '0023_merge_20221114_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='boundary_comparison_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityuploadstatus',
            name='comparison_data_ready',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boundarycomparison',
            name='comparison_boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_boundary', to='georepo.geographicalentity'),
        ),
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='summaries',
            field=models.JSONField(blank=True, help_text='Validation summary', max_length=1024, null=True),
        ),
    ]
