# Generated by Django 4.0.7 on 2022-11-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_entityuploadstatus_boundary_comparison_summary_and_more'),
        ('dashboard', '0024_merge_20221116_1037'),
    ]

    operations = [
    ]
