# Generated by Django 4.0.7 on 2022-11-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_merge_20221117_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Valid', 'Valid'), ('Error', 'Error'), ('Processing', 'Processing'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='', max_length=100),
        ),
    ]
