# Generated by Django 4.0.7 on 2022-11-22 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0026_alter_entityuploadstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOUNDARY_MATCHING', 'BOUNDARY_MATCHING'), ('LAYER_VALIDATION', 'LAYER_VALIDATION'), ('GENERATE_TILES', 'GENERATE_TILES')], max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['created_at'],
            },
        ),
    ]
