# Generated by Django 4.0.7 on 2022-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
