# Generated by Django 4.0.7 on 2022-12-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georepo', '0039_datasetview_task_id'),
        ('dashboard', '0030_entitiesuserconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='revised_entity_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entityuploadstatus',
            name='revised_entity_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='original_geographical_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_geographical_entity', to='georepo.geographicalentity'),
        ),
    ]
