# Generated by Django 4.0.7 on 2022-12-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_entityuploadstatus_max_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='auto_matched_parent_ready',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='layeruploadsession',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Validating', 'Validating'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Error', 'Error'), ('Processing', 'Processing'), ('Reviewing', 'Reviewing'), ('Pre-processing', 'Pre-processing')], max_length=128),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOUNDARY_MATCHING', 'BOUNDARY_MATCHING'), ('LAYER_VALIDATION', 'LAYER_VALIDATION'), ('GENERATE_TILES', 'GENERATE_TILES'), ('PARENT_MATCHING', 'PARENT_MATCHING')], max_length=100),
        ),
        migrations.CreateModel(
            name='EntityUploadChildLv1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=300)),
                ('parent_entity_id', models.CharField(max_length=100)),
                ('is_parent_rematched', models.BooleanField(default=False, help_text='True if rematched parent has different default code')),
                ('poi_distance', models.FloatField(blank=True, null=True)),
                ('entity_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entityuploadstatus')),
            ],
        ),
    ]
