# Generated by Django 4.0.7 on 2022-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_layeruploadsession_auto_matched_parent_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundarycomparison',
            name='is_parent_rematched',
            field=models.BooleanField(default=False, help_text='True if rematched parent has different default code'),
        ),
    ]
