# Generated by Django 4.0.7 on 2023-01-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_boundarycomparison_is_parent_rematched'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='historical_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layeruploadsession',
            name='historical_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layeruploadsession',
            name='is_historical_upload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
