# Generated by Django 4.0.7 on 2023-01-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_entityuploadstatus_max_level_in_layer_and_more'),
        ('dashboard', '0035_layeruploadsession_historical_end_date_and_more'),
    ]

    operations = [
    ]
