# Generated by Django 4.0.7 on 2023-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_boundarycomparison_geometry_overlap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundarycomparison',
            name='is_same_entity',
            field=models.BooleanField(blank=True, help_text='Same entity concept, True if both similarities are above thresholds. This can be manually changed by end user', null=True),
        ),
    ]
