# Generated by Django 4.0.7 on 2023-01-19 08:00

from django.db import migrations


def patch_boundary_summary_data(apps, schema_editor):
    EntityUploadStatus = apps.get_model('dashboard', 'EntityUploadStatus')
    uploads = EntityUploadStatus.objects.exclude(
        boundary_comparison_summary__isnull=True
    )
    for upload in uploads:
        summaries = upload.boundary_comparison_summary
        for summary in summaries:
            if 'avg_similarity' in summary:
                summary['avg_similarity_new'] = summary['avg_similarity']
                summary['avg_similarity_old'] = 0
                del summary['avg_similarity']
        upload.boundary_comparison_summary = summaries
        upload.save()


def patch_boundary_comparison_data(apps, schema_editor):
    BoundaryComparison = apps.get_model('dashboard', 'BoundaryComparison')
    comparisons = BoundaryComparison.objects.filter(
        geometry_overlap_old__isnull=True
    )
    for comparison in comparisons:
        # is_same_entity = True if has comparison_boundary
        comparison.is_same_entity = (
            comparison.comparison_boundary is not None
        )
        comparison.geometry_overlap_old = 0
        comparison.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_boundarycomparison_is_same_entity'),
    ]

    operations = [
        migrations.RunPython(patch_boundary_summary_data),
        migrations.RunPython(patch_boundary_comparison_data),
    ]
