# Generated by Django 4.0.7 on 2023-01-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_patch_boundary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadchildlv1',
            name='feature_index',
            field=models.IntegerField(default=-1, help_text='Index in layer file'),
        ),
    ]
