# Generated by Django 4.0.7 on 2023-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_patch_boundary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='admin_level_names',
            field=models.JSONField(blank=True, default={}, help_text='Name of admin levels', null=True),
        ),
    ]
