# Generated by Django 4.0.7 on 2023-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_patch_boundary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitiesuserconfig',
            name='query_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
