# Generated by Django 4.0.7 on 2023-01-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_entitiesuserconfig_query_string'),
        ('dashboard', '0041_entityuploadchildlv1_feature_index'),
    ]

    operations = [
    ]
