# Generated by Django 4.0.7 on 2023-01-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_entityuploadstatus_admin_level_names'),
        ('dashboard', '0042_merge_20230127_0238'),
    ]

    operations = [
    ]
