# Generated by Django 4.0.7 on 2023-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_layerconfig_boundary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='revision_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
