# Generated by Django 4.0.7 on 2023-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_entityuploadstatus_revision_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='running task id', max_length=256),
        ),
        migrations.AlterField(
            model_name='layeruploadsession',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='running task id', max_length=256),
        ),
    ]
