# Generated by Django 4.0.7 on 2023-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_entityuploadstatus_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerconfig',
            name='privacy_level',
            field=models.CharField(blank=True, default='', help_text='user input privacy level', max_length=255),
        ),
        migrations.AddField(
            model_name='layerconfig',
            name='privacy_level_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='privacy_level',
            field=models.CharField(blank=True, default='', help_text='user input privacy level', max_length=255),
        ),
        migrations.AddField(
            model_name='layerfile',
            name='privacy_level_field',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
