# Generated by Django 4.0.7 on 2023-03-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_layerconfig_privacy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='unique_code_version',
            field=models.FloatField(blank=True, help_text='All entities will have same version', null=True),
        ),
    ]
