# Generated by Django 4.0.7 on 2023-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_entityuploadstatus_unique_code_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Valid', 'Valid'), ('Error', 'Error'), ('Processing', 'Processing'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processing_Approval', 'Processing_Approval')], default='', max_length=100),
        ),
    ]
