# Generated by Django 4.0.7 on 2023-05-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_entityuploadstatus_status'),
        ('dashboard', '0050_layeruploadsession_gaps_threshold_and_more'),
    ]

    operations = [
    ]
