# Generated by Django 4.0.7 on 2023-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_merge_20230505_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='progress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
