# Generated by Django 4.0.7 on 2023-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_entityuploadstatus_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitiesuserconfig',
            name='concept_ucode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
