# Generated by Django 4.0.7 on 2023-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_entitiesuserconfig_concept_ucode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityuploadchildlv1',
            name='poi_distance',
        ),
        migrations.AddField(
            model_name='entityuploadchildlv1',
            name='overlap_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
