# Generated by Django 4.0.7 on 2023-06-02 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_batchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='scheduled_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='scheduled_from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
