# Generated by Django 4.0.7 on 2023-07-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_maintenance_scheduled_end_date_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """create or replace function SimplifyGeometry(geom geometry, tolerance float8)
                returns geometry
                language plpgsql immutable as
            $func$
            declare
                env geometry;
            begin
                if tolerance = 0 then
                    return geom;
                end if;
                env := ST_MakeEnvelope(-180, -85.0511287798066, 180, 85.0511287798066, 4326);
                if ST_Covers(env, geom) then
                    return ST_SimplifyVW(geom, tolerance);
                else
                    return ST_SimplifyVW(ST_Intersection(env, geom), tolerance);
                end if;
            end;
            $func$;""",
            reverse_sql="""drop function if exists
                SimplifyGeometry(geom geometry, tolerance float8) restrict;""",
            elidable=False
        )
    ]
