# Generated by Django 4.0.7 on 2023-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_privacylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOUNDARY_MATCHING', 'BOUNDARY_MATCHING'), ('LAYER_VALIDATION', 'LAYER_VALIDATION'), ('GENERATE_TILES', 'GENERATE_TILES'), ('PARENT_MATCHING', 'PARENT_MATCHING'), ('BATCH_REVIEW', 'BATCH_REVIEW')], max_length=100),
        ),
    ]
