# Generated by Django 4.0.7 on 2023-08-16 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_add_transform_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
