# Generated by Django 4.0.7 on 2023-09-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_update_transform_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
