# Generated by Django 4.0.7 on 2023-09-13 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_layerfile_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_size', models.FloatField(default=0)),
            ],
        ),
    ]
