# Generated by Django 4.0.7 on 2023-09-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_entityuploadstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerUploadSessionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0_default_codes', models.JSONField(blank=True, default=list, null=True)),
                ('total_adm0', models.IntegerField(blank=True, default=0, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.layeruploadsession')),
            ],
        ),
    ]
