# Generated by Django 4.0.7 on 2023-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_layeruploadsessionactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsessionactionlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='layeruploadsessionactionlog',
            name='task_id',
            field=models.CharField(blank=True, default='', help_text='running task id', max_length=256),
        ),
    ]
