# Generated by Django 4.0.7 on 2023-09-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_layeruploadsession_current_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsessionactionlog',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
