# Generated by Django 4.0.7 on 2023-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_layeruploadsessionactionlog_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsessionactionlog',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Error', 'Error'), ('Processing', 'Processing')], default='Pending', max_length=128),
        ),
    ]
