# Generated by Django 4.0.7 on 2023-09-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_layeruploadsessionactionlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layeruploadsessionactionlog',
            name='state_from',
        ),
        migrations.RemoveField(
            model_name='layeruploadsessionactionlog',
            name='state_to',
        ),
    ]
