# Generated by Django 4.0.7 on 2023-09-28 02:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_alter_layeruploadsession_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField(default=-1)),
                ('level', models.IntegerField(default=0)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=100)),
                ('parent_entity_id', models.CharField(max_length=100)),
                ('ancestor_entity_id', models.CharField(max_length=100)),
                ('layer_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.layerfile')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.layeruploadsession')),
            ],
        ),
    ]
