# Generated by Django 4.0.7 on 2023-09-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_entitytemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytemp',
            name='ancestor_entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entitytemp',
            name='parent_entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
