# Generated by Django 4.0.7 on 2023-09-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_entitytemp_ancestor_entity_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entitytemp',
            index=models.Index(fields=['level', 'entity_id'], name='dashboard_e_level_47c2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytemp',
            index=models.Index(fields=['level', 'ancestor_entity_id'], name='dashboard_e_level_17f50e_idx'),
        ),
    ]
