# Generated by Django 4.0.7 on 2023-10-23 18:24

from django.db import migrations, models


def patch_previous_status(apps, schema_editor):
    EntityUploadStatus = apps.get_model('dashboard', 'EntityUploadStatus')
    uploads = EntityUploadStatus.objects.filter(status='Error Processing')
    uploads.update(status='Stopped with Error')
    

def reverse_patch_previous_status(apps, schema_editor):
    EntityUploadStatus = apps.get_model('dashboard', 'EntityUploadStatus')
    uploads = EntityUploadStatus.objects.filter(status='Stopped with Error')
    uploads.update(status='Error Processing')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_alter_entityuploadstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityuploadstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Valid', 'Valid'), ('Warning', 'Warning'), ('Error', 'Error'), ('Processing', 'Processing'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processing_Approval', 'Processing_Approval'), ('Stopped with Error', 'Stopped with Error')], default='', max_length=100),
        ),
        migrations.RunPython(patch_previous_status, reverse_patch_previous_status),
    ]
