# Generated by Django 4.0.7 on 2023-12-12 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georepo', '0133_auto_20231127_0912'),
        ('dashboard', '0083_entitytemp_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEntityEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('submitted_on', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('last_min_poll_count', models.IntegerField(default=0)),
                ('last_min_poll_at', models.DateTimeField(blank=True, null=True)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='batch_entity_edit/input/%Y/%m/%d/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='batch_entity_edit/output/%Y/%m/%d/')),
                ('id_fields', models.JSONField(blank=True, default=list)),
                ('name_fields', models.JSONField(blank=True, default=list)),
                ('ucode_field', models.CharField(blank=True, default='', max_length=512)),
                ('error_notes', models.TextField(blank=True, null=True)),
                ('success_notes', models.TextField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georepo.dataset')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
