# Generated by Django 4.0.7 on 2024-01-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_batchentityedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchentityedit',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
