# Generated by Django 4.0.7 on 2024-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_batchentityedit_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOUNDARY_MATCHING', 'BOUNDARY_MATCHING'), ('LAYER_VALIDATION', 'LAYER_VALIDATION'), ('GENERATE_TILES', 'GENERATE_TILES'), ('PARENT_MATCHING', 'PARENT_MATCHING'), ('BATCH_REVIEW', 'BATCH_REVIEW'), ('BATCH_ENTITY_EDIT', 'BATCH_ENTITY_EDIT')], max_length=100),
        ),
    ]
