# Generated by Django 4.0.7 on 2024-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchentityedit',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='batch_entity_edit/preview/%Y/%m/%d/'),
        ),
    ]
