# Generated by Django 4.0.7 on 2024-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityuploadstatus',
            name='allowable_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entityuploadstatus',
            name='blocking_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entityuploadstatus',
            name='superadmin_blocking_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entityuploadstatus',
            name='superadmin_bypass_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
