# Generated by Django 4.0.7 on 2024-05-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_entityuploadstatus_allowable_errors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityEditResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_idx', models.IntegerField(default=-1)),
                ('ucode', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=-1)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('default_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('default_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('new_names', models.JSONField(blank=True, default=list)),
                ('new_codes', models.JSONField(blank=True, default=list)),
                ('batch_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.batchentityedit')),
            ],
        ),
    ]
