# Generated by Django 4.0.7 on 2024-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_entityeditresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='validation_report',
            field=models.FileField(null=True, upload_to='upload_session_reports'),
        ),
        migrations.AddField(
            model_name='layeruploadsession',
            name='validation_summaries',
            field=models.JSONField(default=dict, help_text='Pre-validation summary'),
        ),
    ]
