# Generated by Django 4.0.7 on 2024-07-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_entityeditresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='validation_report',
            field=models.FileField(blank=True, null=True, upload_to='upload_session_reports'),
        ),
        migrations.AddField(
            model_name='layeruploadsession',
            name='validation_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='Pre-validation summary', null=True),
        ),
    ]
