# Generated by Django 4.0.7 on 2024-10-15 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_layeruploadsession_validation_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled_from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
