# Generated by Django 4.0.7 on 2024-10-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_alter_maintenance_scheduled_from_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('storage_log', models.TextField(blank=True, null=True)),
                ('memory_log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
