# Generated by Django 4.0.7 on 2024-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_storagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
