# Generated by Django 4.0.7 on 2025-04-12 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0095_logfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobExportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('submitted_on', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('last_min_poll_count', models.IntegerField(default=0)),
                ('last_min_poll_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(help_text='Path to the blob to be exported', max_length=512)),
                ('output_path', models.CharField(blank=True, help_text='Path to the zip output file', max_length=512, null=True)),
                ('size', models.BigIntegerField(blank=True, help_text='Size of the output file', null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
