# Generated by Django 4.0.7 on 2025-09-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_blobexportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeruploadsession',
            name='disabled_validation',
            field=models.JSONField(blank=True, default=list, help_text='List of disabled validation checks', null=True),
        ),
    ]
