# Generated by Django 4.0.7 on 2025-10-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_layeruploadsession_disabled_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOUNDARY_MATCHING', 'BOUNDARY_MATCHING'), ('LAYER_VALIDATION', 'LAYER_VALIDATION'), ('GENERATE_TILES', 'GENERATE_TILES'), ('PARENT_MATCHING', 'PARENT_MATCHING'), ('BATCH_REVIEW', 'BATCH_REVIEW'), ('BATCH_ENTITY_EDIT', 'BATCH_ENTITY_EDIT'), ('DATASET_VIEW_EXPORTER', 'DATASET_VIEW_EXPORTER'), ('DATASET_EXPORTER', 'DATASET_EXPORTER')], max_length=100),
        ),
    ]
