# Generated by Django 4.0.7 on 2023-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_page_relative_url_alter_block_anchor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='documentation_base_url',
            field=models.CharField(default='https://unicef-drp.github.io/GeoRepo-OS', max_length=512),
        ),
    ]
