[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
childlogdir=/tmp

[program:celery-worker]
command=celery -A core worker -l INFO --logfile=/tmp/master_worker.log
directory=/home/web/django_project
autostart=true
autorestart=true
startretries=100
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:celery-tile]
command=celery -A core worker -l INFO -Q tegola --concurrency=1 --prefetch-multiplier=1 -n tile --logfile=/tmp/tile_worker.log
directory=/home/web/django_project
autostart=true
autorestart=true
startretries=100
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:celery-exporter]
command=celery -A core worker -l INFO -Q exporter --concurrency=1 --prefetch-multiplier=1 -n exporter --logfile=/tmp/exporter_worker.log
directory=/home/web/django_project
autostart=true
autorestart=true
startretries=100
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:celery-validator]
command=celery -A core worker -l INFO -Q validation --concurrency=3 --prefetch-multiplier=1 -n validate --logfile=/tmp/validation_worker.log
directory=/home/web/django_project
autostart=true
autorestart=true
startretries=100
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
