# Generated by Django 4.0.7 on 2023-07-24 17:20

from django.db import migrations
import re

def patch_existing_user_emails(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.filter(email__startswith='live.com#'):
        user.email = re.sub(r'^live\.com#', '', user.email)
        user.username = user.email
        user.save()

def reverse_patch_existing_user_emails(apps, schema_editor):
    """Do nothing for reverse func"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('azure_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(patch_existing_user_emails, reverse_patch_existing_user_emails),
    ]
