# Generated by Django 4.0.7 on 2023-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_auth', '0002_remove_email_liveprefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('client_id', models.CharField(max_length=256, unique=True)),
                ('origin', models.CharField(help_text='Domain with protocol, e.g. https://domainA.com', max_length=256)),
            ],
        ),
    ]
