# Generated by Django 4.0.7 on 2023-08-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_auth', '0003_thirdpartyapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThirdPartyApplication',
        ),
    ]
