# Generated by Django 4.0.6 on 2022-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='', max_length=512)),
                ('primary_color', models.CharField(default='#1CABE2', help_text='Main color for the website. Put the hex color with # (e.g. #ffffff) or put the text of color. (e.g. blue)', max_length=16)),
                ('anti_primary_color', models.CharField(default='#FFFFFF', help_text='Anti of primary color that used for text in primary color.', max_length=16)),
                ('secondary_color', models.CharField(default='#374EA2', help_text='Secondary color that used for example for button. ', max_length=16)),
                ('anti_secondary_color', models.CharField(default='#FFFFFF', help_text='Anti of secondary color that used for text in primary color.', max_length=16)),
                ('tertiary_color', models.CharField(default='#297CC2', help_text='Tertiary color that used for example for some special place. ', max_length=16)),
                ('anti_tertiary_color', models.CharField(default='#FFFFFF', help_text='Anti of tertiary color that used for text in primary color.', max_length=16)),
                ('icon', models.FileField(blank=True, null=True, upload_to='settings/icons')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='settings/icons')),
            ],
            options={
                'verbose_name_plural': 'site preferences',
            },
        ),
        migrations.CreateModel(
            name='SitePreferencesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='settings/images')),
                ('title', models.CharField(blank=True, help_text='Title of image.', max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of image.', null=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitepreferences')),
            ],
        ),
    ]
