# Generated by Django 4.0.7 on 2022-12-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='search_similarity',
            field=models.FloatField(blank=True, default=0.3, null=True),
        ),
    ]
