# Generated by Django 4.0.7 on 2022-12-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitepreferences_search_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='search_simplify_tolerance',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
