# Generated by Django 4.0.7 on 2023-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitepreferences_geometry_similarity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='upload_overlaps_error_threshold',
            field=models.FloatField(blank=True, default=0.01, help_text='Threshold for overlaps error in uploader workflow. Value from 0-1. Default to 0.01. Overlaps error below this threshold will be ignored', null=True),
        ),
    ]
