# Generated by Django 4.0.7 on 2023-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitepreferences_upload_overlaps_error_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='geometry_similarity_threshold',
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='geometry_similarity_threshold_new',
            field=models.FloatField(blank=True, default=0.6, help_text='Default threshold of percentage of the new boundary area covered by the old matching boundary (% new). Value from 0-1', null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='geometry_similarity_threshold_old',
            field=models.FloatField(blank=True, default=0.6, help_text='Default threshold of percentage of the old boundary area covered by the new matching boundary (% old). Value from 0-1', null=True),
        ),
    ]
