# Generated by Django 4.0.7 on 2023-01-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sitepreferences_geometry_similarity_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='upload_overlaps_error_threshold',
        ),
    ]
