# Generated by Django 4.0.7 on 2023-01-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitepreferences_upload_overlaps_error_threshold'),
        ('core', '0007_sitepreferences_tile_configs_template'),
    ]

    operations = [
    ]
