# Generated by Django 4.0.7 on 2023-01-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20230127_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='short_code_exclusion',
            field=models.CharField(default='OAB', help_text='Dataset short code to be excluded from UCode generation. Comma separated', max_length=256),
        ),
    ]
