# Generated by Django 4.0.7 on 2023-01-31 14:22

from django.db import migrations, models


def init_default_level_names_template(apps, schema_editor):
    SitePreferences = apps.get_model('core', 'SitePreferences')
    preferences, _ = SitePreferences.objects.get_or_create(pk=1)
    preferences.level_names_template = [
        {
            'level': 0,
            'label': 'Country'
        },
        {
            'level': 1,
            'label': 'Province'
        },
        {
            'level': 2,
            'label': 'District'
        },
        {
            'level': 3,
            'label': 'Sub-district'
        }
    ]
    preferences.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitepreferences_short_code_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='level_names_template',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.RunPython(init_default_level_names_template),
    ]
