# Generated by Django 4.0.7 on 2023-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitepreferences_level_names_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='api_config',
            field=models.JSONField(blank=True, default={'default_page_size': 30, 'max_page_size': 30}),
        ),
    ]
