# Generated by Django 4.0.7 on 2023-02-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitepreferences_api_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='api_latest_version',
            field=models.CharField(default='v1', help_text='API current latest version - Usage in background task that generates URL', max_length=20),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='metadata_xml_config',
            field=models.JSONField(blank=True, default={'ContactName': 'GeoRepo', 'ContactOrg': 'Unicef', 'ContactPosition': 'Administrator', 'License': 'Not Specified: The original author did not specify a license.'}),
        ),
    ]
