# Generated by Django 4.0.7 on 2023-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitepreferences_api_latest_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='default_public_groups',
            field=models.JSONField(blank=True, default=['UNICEF']),
        ),
    ]
