# Generated by Django 4.0.7 on 2023-03-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitepreferences_default_public_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='api_config',
            field=models.JSONField(blank=True, default={'default_page_size': 50, 'max_page_size': 50}),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='geometry_similarity_threshold_new',
            field=models.FloatField(blank=True, default=0.9, help_text='Default threshold of percentage of the new boundary area covered by the old matching boundary (% new). Value from 0-1', null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='geometry_similarity_threshold_old',
            field=models.FloatField(blank=True, default=0.9, help_text='Default threshold of percentage of the old boundary area covered by the new matching boundary (% old). Value from 0-1', null=True),
        ),
    ]
