# Generated by Django 4.0.7 on 2023-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sitepreferences_api_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='maptiler_api_key',
            field=models.CharField(default='', help_text='Used in FrontEnd UI to preview maps', max_length=256),
        ),
    ]
