# Generated by Django 4.0.7 on 2023-04-12 13:38

from django.db import migrations
from django.contrib.auth.hashers import make_password


def patch_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    # do nothing first, we should unset the pw for azure env only
    # for user in User.objects.exclude(username='admin'):
    #     user.password = make_password(None)
    #     user.save()


def reverse_patch_existing_users(apps, schema_editor):
    """Do nothing for reverse func"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitepreferences_maptiler_api_key'),
    ]

    operations = [
        migrations.RunPython(patch_existing_users, reverse_patch_existing_users),
    ]
