# Generated by Django 4.0.7 on 2023-04-17 05:06

from django.db import migrations, models
import django.db.models.deletion


def patch_existing_tokens(apps, schema_editor):
    """Init CustomAPIKey objects from existing tokens"""
    Token = apps.get_model('authtoken', 'Token')
    CustomApiKey = apps.get_model('core', 'CustomApiKey')
    for token in Token.objects.all():
        CustomApiKey.objects.get_or_create(
            token_ptr=token,
            created='2023-04-17 11:44:41.147 +0700',
            user=token.user
        )


def reverse_patch_existing_tokens(apps, schema_editor):
    """Do nothing for reverse func"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('core', '0016_unset_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApiKey',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
            bases=('authtoken.token',),
        ),
        migrations.RunPython(patch_existing_tokens, reverse_patch_existing_tokens),
    ]
