# Generated by Django 4.0.7 on 2023-05-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitepreferences_default_geometry_checker_params'),
        ('core', '0017_customapikey'),
    ]

    operations = [
    ]
