# Generated by Django 4.0.7 on 2023-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitepreferences_default_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='base_url_help_page',
            field=models.CharField(default='', help_text='Used in FrontEnd UI to scraping help text', max_length=256),
        ),
    ]
