# Generated by Django 4.0.7 on 2023-08-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('core', '0022_customapikey_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='knox.authtoken')),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.AlterModelOptions(
            name='customapikey',
            options={'verbose_name': 'API Key (Depr)', 'verbose_name_plural': 'API Keys (Depr)'},
        ),
    ]
