# Generated by Django 4.0.7 on 2023-08-29 02:43

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_apikey_alter_customapikey_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomApiKey',
        ),
    ]
