# Generated by Django 4.0.7 on 2023-08-29 02:54

from django.db import migrations


def delete_tokens(apps, schema_editor):
    try:
        Token = apps.get_model("authtoken", "token")
    except LookupError:
        Token = False
    
    if Token:
        db_alias = schema_editor.connection.alias
        Token.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_customapikey'),
    ]

    operations = [
        migrations.RunPython(delete_tokens)
    ]
