# Generated by Django 4.0.7 on 2023-09-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_old_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='swagger_ui_info',
            field=models.TextField(default='', help_text='Shown as the introduction at the top of Swagger UI. HTML and Markdown supported.'),
        ),
    ]
