# Generated by Django 4.0.7 on 2023-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_update_tiling_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='swagger_ui_info',
            field=models.TextField(default='', help_text='Shown as the introduction at the top of Swagger UI. HTML and Markdown supported.'),
        ),
    ]
