# Generated by Django 4.0.7 on 2023-09-29 02:38

import core.models.preferences
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_sitepreferences_swagger_ui_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='base_url_help_page',
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='api_config',
            field=models.JSONField(blank=True, default=core.models.preferences.default_api_config, help_text='API pagination configuration.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='default_admin_emails',
            field=models.JSONField(blank=True, default=list, help_text='For sending email when there is sign-up/access request.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='default_geometry_checker_params',
            field=models.JSONField(blank=True, default=core.models.preferences.default_geometry_checker_params, help_text='Default parameters for geometry validation.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='default_public_groups',
            field=models.JSONField(blank=True, default=core.models.preferences.default_public_groups, help_text='Default group that cannot be removed from system.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='level_names_template',
            field=models.JSONField(blank=True, default=list, help_text='Default admin level names.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='metadata_xml_config',
            field=models.JSONField(blank=True, default=core.models.preferences.default_metadata_xml_config, help_text='Metadata xml configuration for export data.'),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='search_similarity',
            field=models.FloatField(blank=True, default=0.3, help_text='Search Similarity Threshold for fuzzy search.', null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='search_simplify_tolerance',
            field=models.FloatField(blank=True, default=0.5, help_text='Simplify tolerance for geometry fuzzy search.', null=True),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='tile_configs_template',
            field=models.JSONField(blank=True, default=list, help_text='Default simplification tiling config.'),
        ),
    ]
