# Generated by Django 4.0.7 on 2023-11-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_sitepreferences_base_url_help_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='search_similarity',
            field=models.FloatField(blank=True, default=0.4, help_text='Search Similarity Threshold for fuzzy search.', null=True),
        ),
    ]
