# Generated by Django 4.0.7 on 2024-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_sitepreferences_search_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='blob_storage_domain_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='Whitelist for domain to be set in CORS rule of azure blob storage.'),
        ),
    ]
