# Generated by Django 4.0.7 on 2024-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_sitepreferences_login_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='ephemeral_paths',
            field=models.JSONField(blank=True, default=list, help_text='List of path to monitor the size and send to sentry.', null=True),
        ),
    ]
