# Generated by Django 4.0.7 on 2024-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sitepreferences_ephemeral_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='storage_checker_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for storage checker job.', null=True),
        ),
    ]
