# Generated by Django 4.0.7 on 2025-02-19 20:44

import core.models.preferences
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sitepreferences_storage_checker_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreferences',
            name='api_config',
            field=models.JSONField(blank=True, default=core.models.preferences.default_api_config, help_text='API configuration.'),
        ),
    ]
