# Generated by Django 4.0.7 on 2025-10-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_apirequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='mapshaper_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for mapshaper simplification.', null=True),
        ),
    ]
