# Generated by Django 4.0.7 on 2026-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sitepreferences_mapshaper_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(db_index=True, max_length=255)),
                ('command_args', models.JSONField(blank=True, default=list)),
                ('command_kwargs', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['-created_at', 'status'], name='core_comman_created_640a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['command_name', '-created_at'], name='core_comman_command_38a43f_idx'),
        ),
    ]
