SHELL := /bin/bash

run:
	@echo
	@echo "------------------------------------------------------------------"
	@echo "Run the docs container"
	@echo "Can be accessed in http://localhost:8000/"
	@echo "------------------------------------------------------------------"
	mkdocs serve

