# NOTE: change in tag, please also change API_ORDERS
SEARCH_MODULE_TAG = '01-search-module'
SEARCH_DATASET_TAG = '02-search-dataset'
SEARCH_DATASET_ENTITY_TAG = '03-search-dataset-entity'
SEARCH_VIEW_TAG = '04-search-view'
SEARCH_VIEW_ENTITY_TAG = '05-search-view-entity'
OPERATION_VIEW_ENTITY_TAG = '06-operation-view-entity'
DOWNLOAD_DATA_TAG = '07-download'
CONTROLLED_LIST_TAG = '08-controlled-list'
SEARCH_ENTITY_TAG = '97-search-entity'
OPERATION_ENTITY_TAG = '98-operation-entity'
DOWNLOAD_DATA_BY_DATASET_TAG = '99-download'
